import { ejercicios } from "./ejercicios_resueltos.js";
ejercicios.concade("Kevin");
ejercicios.recorte("Bienvenido", 2);
ejercicios.arra("Hola que tal", " ");
ejercicios.repetir("Hola mundo", 3);
ejercicios.inverte("Hola Kevin");
ejercicios.contarvece("Holas s ", "s");
ejercicios.frase("salas");
ejercicios.patron("xyz1 xyz2 xyz3", "xy");
ejercicios.eje9();
ejercicios.eje10(1001);
ejercicios.eje11(5);
ejercicios.eje12(6);
ejercicios.eje13(6);
ejercicios.eje14(86, "f");
ejercicios.eje15(100, 2);
ejercicios.eje16(1000, 20);
//ejercicios.eje17("1998,09,29");
ejercicios.eje18("s");
ejercicios.eje19("kevin Alenxader");
ejercicios.eje20("kevinchacha29@yahoo.com");
